import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/global/Navbar";
import { SidebarProvider } from "@/components/ui/sidebar";
import AppSidebar from "@/components/global/AppSidebar";



const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default  function RootLayout({ children }) {

  return (
    
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased  flex    `}
      >
        
        <SidebarProvider >
            <AppSidebar />
        <main className="w-full mt-3 ">
          <Navbar />
          <div className="">{children}</div>
        </main>
        </SidebarProvider>
      </body>
    </html>
  );
}
